exports.START = 'main:start'
exports.END = 'main:end'

exports.REPOS_LOAD = 'repos:load'
exports.LIST_REPOS = 'repos:list'
exports.CURRENT_REPO = 'repos:current'
exports.ADD_REPO = 'repos:add'
exports.ADD_REPO_IN_LIST = 'repos:add_in_list'
exports.CHANGE_CURRENT_REPO = 'repos:change_current'
exports.CHANGE_REPO = 'repos:change'
exports.SELECT_REPO = 'repos:select'
exports.REMOVE_REPO = 'repos:remove'
exports.OPEN_REPO = 'repos:open'
