exports.START = 'main:start'
exports.END = 'main:end'

exports.REPOS_LOAD = 'repos:load'
exports.LIST_REPOS = 'repos:list'
exports.CURRENT_REPO = 'repos:current'
exports.ADD_REPO = 'repos:add'
exports.ADD_REPO_IN_LIST = 'repos:add_in_list'
exports.CHANGE_CURRENT_REPO = 'repos:change_current'
exports.CHANGE_REPO = 'repos:change'
exports.SELECT_REPO = 'repos:select'
exports.REMOVE_REPO = 'repos:remove'
exports.OPEN_REPO = 'repos:open'

exports.CLEAR_BRANCHES = 'branches:clear'
exports.LIST_BRANCHES = 'branches:list'
exports.CURRENT_BRANCH = 'branches:current'
exports.ADD_BRANCH = 'branches:add'
exports.CHECKOUT_BRANCH = 'branches:checkout'
exports.REMOVE_BRANCH = 'branches:remove'

exports.CLEAR_STATUS = 'status:clear'
exports.UPDATE_STATUS = 'status:update'

exports.FETCH_REQUEST = 'status:fetch:request'
exports.FETCH_LOADING = 'status:fetch:loading'
exports.PULL_REQUEST = 'status:pull:request'
exports.PULL_LOADING = 'status:pull:loading'
exports.PUSH_REQUEST = 'status:push:request'
exports.PUSH_LOADING = 'status:push:loading'

exports.LOG_LOAD = 'log:load'
exports.LOG_CLEAR = 'log:clear'
exports.LOG_LIST = 'log:list'
